const menu = [
  {
    id: 1,
    title: 'Whopper® Menü',
    category: 'Whopper® Menü',
    price: 73.99,
    img: './images/item-1.jpeg',
    desc: `Whopper® eti, büyük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, doğranmış marul, domates ve soğandan oluşan bir Burger King® klasiği. Enfes patates kızartması ve içeceğiyle birlikte Whopper® Menü `,
  },
  {
    id: 2,
    title: 'Rodeo Whopper® Menü',
    category: 'Whopper® Menü',
    price: 89.99,
    img: './images/item-2.jpeg',
    desc: `Whopper® eti, büyük boy susamlı sandviç ekmeği, mayonez, doğranmış marul, soğan halkaları, nefis barbekü sosu ve 2 adet cheddar peynirinden oluşan Whopper® lezzeti. Enfes patates kızartması ve içeceğiyle birlikte Rodeo Whopper® Menü `,
  },
  {
    id: 3,
    title: 'Double Whopper® Menü',
    category: 'Whopper® Menü',
    price: 99.99,
    img: './images/item-3.jpeg',
    desc: `İki adet Whopper® eti, büyük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, doğranmış marul, domates ve soğanla, klasik Whopper®  Enfes patates kızartması ve içeceğiyle birlikte Double Whopper® Menü `,
  },
  {
    id: 4,
    title: 'Triple Whopper® Menü',
    category: 'Whopper® Menü',
    price: 109.99,
    img: './images/item-4.jpeg',
    desc: `3 adet Whopper® eti, büyük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, göbek salata, domates ve soğandan oluşan nefis bir seçim. Enfes patates kızartması ve içeceğiyle birlikte Triple Whopper® Menü `,
  },
  {
    id: 5,
    title: 'Whopper Jr.® Menü',
    category: 'Whopper® Menü',
    price: 69.99,
    img: './images/item-5.jpeg',
    desc: `Hamburger eti, küçük boy susamlı sandviç ekmeği, salatalık turşusu, ketçap, mayonez, doğranmış marul, domates ve soğandan oluşan, Whopper®  Enfes patates kızartması ve içeceğiyle birlikte Whopper Jr.®`,
  },
  {
    id: 6,
    title: 'Big King® Menü',
    category: 'Big King® Menü',
    price: 99.99,
    img: './images/item-6.jpeg',
    desc: `2 adet Hamburger eti, 3 katlı özel ekmeği, cheddar peyniri, salatalık turşusu, doğranmış marul ve soğana eşlik eden özel Big King® sosun birleşimi. Enfes patates kızartması ve içeceğiyle birlikte Big King® Menü`,
  },
  {
    id: 7,
    title: 'Big King XXL® Menü',
    category: 'Big King® Menü',
    price: 129.99,
    img: './images/item-7.jpeg',
    desc: `2 adet Whopper® eti, büyük boy susamlı sandviç ekmeği, 4 adet cheddar peyniri, salatalık turşusu, doğranmış marul, soğan. Enfes patates kızartması ve içeceğiyle birlikte Big King XXL® Menü`,
  },
  {
    id: 8,
    title: 'Double Big King® Menü',
    category: 'Big King® Menü',
    price: 139.99,
    img: './images/item-8.jpeg',
    desc: `4 adet Hamburger eti, 3 katlı özel ekmeği, cheddar peyniri, salatalık turşusu, doğranmış marul ve soğana eşlik eden özel Big King® sosun birleşimi. Enfes patates kızartması ve içeceğiyle birlikte Double Big King® Menü `,
  },
  {
    id: 9,
    title: 'Big King®Jr. Menü',
    category: 'Big King® Menü',
    price: 79.99,
    img: './images/item-9.jpeg',
    desc: `Hamburger eti, küçük boy susamlı sandviç ekmeği, cheddar peyniri, salatalık turşusu, doğranmış marul ve soğana eşlik eden özel Big King® sosun birleşimi. Enfes patates kızartması ve içeceğiyle birlikte Big King®Jr. Menü.`,
  },
  {
    id: 10,
    title: 'BK Crispy Chicken Menü',
    category: 'Chicken Menü',
    price: 63.99,
    img: './images/item-10.jpeg',
    desc: `Mısır gevreği kaplı çıtır çıtır tavuğu ve lezzetli acısıyla bir Burger King® lezzeti! Enfes patates kızartması ve içeceğiyle birlikte BK Crispy Chicken Menü keyfini istediğin gibi yaşa!`,
  },
  {
    id: 11,
    title: 'King Chicken® ',
    category: 'Chicken Menü',
    price: 78.99,
    img: './images/item-11.jpg',
    desc: `King Chicken eti, susamlı sandviç ekmeği, mayonez ve doğranmış maruldan oluşan bu son derece sade alternatifi, enfes patates kızartması ve içeceğiyle birlikte istediğin gibi yaşa!`,
  },
  {
    id: 12,
    title: 'Double King Chicken® ',
    category: 'Chicken Menü',
    price: 84.99,
    img: './images/item-12.jpeg',
    desc: `2 adet King Chicken® eti, susamlı sandviç ekmeği, mayonez ve doğranmış maruldan oluşan klasikleşmiş lezzet alternatifini, enfes patates kızartması ve içeceğiyle birlikte istediğin gibi yaşa!`,
  },
];
export default menu;